- name: Setup .NET
  uses: actions/setup-dotnet@v4
  with:
    dotnet-version: '6.0.x'

- name: Restore
  run: dotnet restore inventory.csproj

- name: Build
  run: dotnet build inventory.csproj --configuration Release --no-restore

- name: Publish
  run: dotnet publish inventory.csproj -c Release -o ${{ env.DOTNET_ROOT }}/myapp
